### ISSUE TITLE
armhf and arm64 builds

### ISSUE THREAD

**Issue by sebdanielsson** [claws/dump1090-exporter#44]
Anyway you could build the image for armhf and arm64/aarch64 as well? Would be great for running on a Raspberry Pi!

**Comment by mateuszdrab** [comment]
Check out my fork where I modified the CI pipeline to build a multiarch image

`ghcr.io/mateuszdrab/dump1090-exporter:master`

**Comment by sebdanielsson** [comment]
Hi! Thanks, just tried the image and got this error message. Any ideas?

```
sudo docker run -p 9105:9105 ghcr.io/mateuszdrab/dump1090-exporter:master --name dump1090exporter --network=host --resource-path=http://localhost:80/dump1090/data --latitude=-60.xxxx --longitude=15.xxxx
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.10/site-packages/dump1090exporter/__init__.py", line 1, in <module>
    from .exporter import Dump1090Exporter
  File "/usr/local/lib/python3.10/site-packages/dump1090exporter/exporter.py", line 6, in <module>
    import asyncio
  File "/usr/local/lib/python3.10/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/local/lib/python3.10/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
    _startTime = time.time()
PermissionError: [Errno 1] Operation not permitted
```

**Comment by mateuszdrab** [comment]
> Hi! Thanks, just tried the image and got this error message. Any ideas?
> 
> ```
> sudo docker run -p 9105:9105 ghcr.io/mateuszdrab/dump1090-exporter:master --name dump1090exporter --network=host --resource-path=http://localhost:80/dump1090/data --latitude=-60.xxxx --longitude=15.xxxx
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
>     __import__(pkg_name)
>   File "/usr/local/lib/python3.10/site-packages/dump1090exporter/__init__.py", line 1, in <module>
>     from .exporter import Dump1090Exporter
>   File "/usr/local/lib/python3.10/site-packages/dump1090exporter/exporter.py", line 6, in <module>
>     import asyncio
>   File "/usr/local/lib/python3.10/asyncio/__init__.py", line 8, in <module>
>     from .base_events import *
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 18, in <module>
>     import concurrent.futures
>   File "/usr/local/lib/python3.10/concurrent/futures/__init__.py", line 8, in <module>
>     from concurrent.futures._base import (FIRST_COMPLETED,
>   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 7, in <module>
>     import logging
>   File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
>     _startTime = time.time()
> PermissionError: [Errno 1] Operation not permitted
> ```

You gotta start the container as privileged and I think pass through the device as well
`--device=/dev/bus/usb:/dev/bus/usb`
