### ISSUE TITLE
Installing dump1090exporter on Raspbian Bookworm

### ISSUE THREAD

**Issue by jayant4001** [claws/dump1090-exporter#45]
I'm unable to install dump1090exporter on Raspbian Bookworm. The pip3 installer shows an error while building aiohttp which looks like an upstream problem. I'm trying to install it in a venv virtual environment since Bookworm mandates this, but having no luck so far. Here's an excerpt from the installer log:

`  running build_ext
  building 'aiohttp._websocket' extension
  creating build/temp.linux-armv7l-cpython-311
  creating build/temp.linux-armv7l-cpython-311/aiohttp
  arm-linux-gnueabihf-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fwrapv -O2 -fPIC -I/home/pi/.venv/include -I/usr/include/python3.11 -c aiohttp/_websocket.c -o build/temp.linux-armv7l-cpython-311/aiohttp/_websocket.o
  aiohttp/_websocket.c:198:12: fatal error: longintrepr.h: No such file or directory
    198 |   #include "longintrepr.h"
        |            ^~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
  error: subprocess-exited-with-error

  × Building wheel for aiohttp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/pi/.venv/bin/python3 /home/pi/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmp4n7tuc05
  cwd: /tmp/pip-install-2ru_r81j/aiohttp_7f7813ea088c4534b94f5324883d26e6
  Building wheel for aiohttp (pyproject.toml) ... error
  ERROR: Failed building wheel for aiohttp
Failed to build aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "/home/pi/.venv/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/home/pi/.venv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.venv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 477, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects
Removed build tracker: '/tmp/pip-build-tracker-mk_ya9cu'
`

If anyone has managed to get around this, please let me know.

Thanks
Jayant

**Comment by rfpronk** [comment]
I ran into the same after dist upgrading my Pi from Bullseye to Bookworm. 
Only a dependency failed so I'm forcing that to a newer version and that works

```
sudo pip3 install --upgrade --break-system-packages --force-reinstall dump1090exporter aiohttp==3.10.10
```

**Comment by jayant4001** [comment]
Thanks mate! I'll try that out. I guess you didn't go the venv route and used break-system-packages instead.
